config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get "about", to:"pages#about"
  resources :articles
  get "signup", to:"users#new"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles
    validates :usersname, presence: true, 
                            uniqueness: { case_sensitive: false }, 
                            length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: {maximum: 105},
                        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end

    def index
        @articles= Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article=Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article 
          else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article 
          else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private
    def set_article
        @article= Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end
    end
    def show
        @user = User.find(params[:id])
        @articles = @user.articles
    end
    def index
        @users = User.all
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information was successgully updated"
            redirect_to @user
        else
            render 'edit'
        end
    end
    private
    def user_params
        params.require(:user).permit(:usersname, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::SHA256.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.usersname, class: "rounded shadow mx-auto d-block")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
<div class="row justify-content-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <% if article.user %>
                    by <%= link_to article.user.usersname, user_path(article.user) %>
                <% end %>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-decoration-none"%></h5>
                <p class="card-text"><%= truncate(article.description, length: 40) %></p>
                <%= link_to "View", article_path(article), class: "btn btn-outline-success"%>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info"%>
                <%= link_to "Delete", article_path(article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger"%>
            </div>
            <div class="card-footer text-body-secondary">
                <small>Created <%= time_ago_in_words(article.created_at)%> ago,
                Edited <%= time_ago_in_words(article.updated_at)%> ago</small>
            </div>
        </div>
    </div>
</div>
<%end%>
</div>

app/views/articles/_form.html.erb
<div class="container">
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true, data: { turbo: false }) do |f| %>

        <div class="row mb-3">
          <%= f.label :Title, class: "col-sm-2 col-form-label text-white"%></br>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
        </div>

        <div class="row mb-3">
        <%= f.label :Description, class: "col-sm-2 col-form-label text-white" %></br>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
        </div>
        </div>

        <div class="row mb-3 justify-content-center">
          <div class="col-2">
            <%= f.submit class: "btn btn-outline-light btn-lg"%>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
         <%= link_to '[ Cancel and Return to articles listing ]', articles_path, class: "text-info text-decoration-none text-primary"%>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>
  

app/views/articles/index.html.erb
<div class="container">
    <h1 class="text-center mt-4">Listing all articles</h1>

    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'article' %>
    <div class="flickr_pagination btmprt">
        <%= will_paginate @articles, :container => false %>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form' %>

  
  

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>

<div class="container">

<div class="row justify-content-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic"> by
                <%= link_to @article.user.usersname, user_path(@article.user) %>
                <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            </div>
            <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info"%>
                <%= link_to "Delete", article_path(@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger"%>
            </div>
            <div class="card-footer text-body-secondary">
                <small>Created <%= time_ago_in_words(@article.created_at)%> ago,
                Edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
            </div>
        </div>
    </div>
</div>

</div>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom bg-dark pt-4 pb-4">
        <div class="container text-center">
            <span class="text-white">
                Copyright &copy; <%= link_to "ALPHA BLOG", root_path, class: "text-white text-decoration-none" %>
            </span>
        </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %> 
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create new article", new_article_path, class: "dropdown-item"%>
            </li>
            <li><%= link_to "View articles", articles_path, class: "dropdown-item"%>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Article listing', articles_path %> 
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="card text-center text-white">
        <div class="card-body">
            <h2 class="card-title">Alpha Blog</h2>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora, iusto maiores aperiam hic maxime perferendis illum quos</p>
            <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true, data: { turbo: false }) do |f| %>

        <div class="row mb-3">
          <%= f.label :Username, class: "col-sm-2 col-form-label text-white"%></br>
        <div class="col-sm-10">
          <%= f.text_field :usersname, class: "form-control shadow rounded", placeholder: "Enter a username" %>
        </div>
        </div>

        <div class="row mb-3">
        <%= f.label :Email, class: "col-sm-2 col-form-label text-white" %></br>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
        </div>
        </div>

        <div class="row mb-3">
        <%= f.label :Password, class: "col-sm-2 col-form-label text-white" %></br>
        <div class="col-sm-10">
          <%= f.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Enter your password" %>
        </div>
        </div>

        <div class="row mb-3 justify-content-center">
          <div class="col-2">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-outline-light btn-lg")%>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
         <%= link_to '[ Cancel and Return to articles listing ]', articles_path, class: "text-info text-decoration-none text-primary"%>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>
  

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
<% @users.each do |user| %>
<div class="row justify-content-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <%= link_to user.usersname, user %>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to gravatar_for(user, size: 150), user%>
                </h5>
                <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                <%= link_to "View Profile", user, class: "btn btn-outline-success"%>
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info"%>
            </div>
            <div class="card-footer text-body-secondary">
                <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
        </div>
    </div>
</div>
<%end%>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.usersname %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article' %>